openapi: "3.0.0"

info:
  version: ”1.0.0”
  title: ”Shop Review API"

paths:
  "/shops/{shopId}/reviews":
    parameters:
      - name: shopId
        in: path
        required: true
        schema: { type: string }

    get:
      summary: "Get shop reviews"
      tags: ["reviews"]
      responses:
        "200":
          description: "Success operation"
    post:
      summary: "Create new reviews"
      tags: ["reviews"]
      responses:
        "201":
          description: "Success operation"
